name: Deploy to prod env
on:
  release:
    types: [released]
jobs:
  build-smart-contract:
    name: "Smart Contract"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: npm install -g yarn
      - name: Compile & Test
        run: |
          yarn
          yarn test
  build-and-deploy-frontend-for-bsc:
    name: BSC
    runs-on: ubuntu-latest
    env:
      working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: npm install -g yarn
        working-directory: ${{env.working-directory}}
      - name: Build Smart Contract artifacts
        run: |
          yarn
          yarn compile
        working-directory: "."
      - name: Compile & Test
        run: |
          yarn
          yarn build
          yarn test:unit
        working-directory: ${{env.working-directory}}
      - name: Deploy to bsc.banano.cc
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_BSC_MAINNET_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: frontend/dist
  build-and-deploy-frontend-for-polygon:
    name: Polygon
    runs-on: ubuntu-latest
    env:
      working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: npm install -g yarn
        working-directory: ${{env.working-directory}}
      - name: Build Smart Contract artifacts
        run: |
          yarn
          yarn compile
        working-directory: "."
      - name: Compile & Test
        run: |
          yarn
          NODE_ENV=production yarn build --mode polygon
          yarn test:unit
        working-directory: ${{env.working-directory}}
      - name: Deploy to polygon.banano.cc
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_POLYGON_MAINNET_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: frontend/dist
  build-and-deploy-frontend-for-fantom:
    name: Fantom
    runs-on: ubuntu-latest
    env:
      working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: npm install -g yarn
        working-directory: ${{env.working-directory}}
      - name: Build Smart Contract artifacts
        run: |
          yarn
          yarn compile
        working-directory: "."
      - name: Compile & Test
        run: |
          yarn
          NODE_ENV=production yarn build --mode fantom
          yarn test:unit
        working-directory: ${{env.working-directory}}
      - name: Deploy to fantom.banano.cc
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_FANTOM_MAINNET_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: frontend/dist
